# Generated by Django 2.2.4 on 2019-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('pdate', models.CharField(max_length=30)),
            ],
        ),
    ]
