# Generated by Django 2.2.4 on 2019-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ptime',
            field=models.CharField(default='06-54-12', max_length=30),
            preserve_default=False,
        ),
    ]
