# Generated by Django 2.2.4 on 2019-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190819_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prepaidplans',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='comment',
            name='cdate',
            field=models.CharField(default='20-08-2019', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='ctime',
            field=models.CharField(default='07-53-43', max_length=30),
            preserve_default=False,
        ),
    ]
